---
apiVersion: v1
kind: Namespace
metadata:
  name: openhab
---
apiVersion: v1
kind: Service
metadata:
  name: app-governing
  namespace: openhab
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
  namespace: openhab
spec:
  selector:
    matchLabels:
      app: openhab
  serviceName: app-governing
  template:
    metadata:
      labels:
        app: openhab
    spec:
      containers:
      - name: app
        image: openhab/openhab:2.4.0
